mesh:
  builtin: true
  name: BoxMesh 10 10 10 1 1 1
  refs: 0
options:
  manufactured: false
  strong_boundary: [5,6] # plane z == 0 and z == Lz
  weak_boundary: none
solver:
  grad_desc: none
  ksp_type: gmres
  ls_type: none
  pc_type: gamg
time:
  num: 1
  save_every: 1
  step: 1
vis:
  normal: upward