mesh:
  builtin: true
  name: BoxMesh 10 10 10 1 1 1
  radius: 1 # the characteristic length for non-dimensionalization
  refs: 0
options:
  nondim: false
  strong_boundary: [5,6] # plane z == 0 and z == Lz
  weak_boundary: none
pde:
  formulation: default
  grad_desc: true
  gd_ls: none
  solver: dynamic
  tol_u: 2.0
  tol_l: 0.2
  tol: 1.0e-8
solver:
  ksp_type: gmres
  pc_type: gamg
time:
  num: 1
  save_every: 1
  step: 1
vis:
  normal: upward